@host = http://localhost:8080/api
@authorization = eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxNjQ1MzM5Yi0zMmY4LTRjOTktYjBjOC0wMDJlMzVhYzhkOTMiLCJlbWFpbCI6ImdhdXJhdkBnbWFpLmNvbSIsImlhdCI6MTc1NzgwNjgzNywiZXhwIjoxNzU3ODA3NDM3fQ.PWL6E_nOR5Ev51cKykuvmfTjvPtNTu9oN6P5u4VBpa0

### Delete patient by ID
@patientId = 4bb20f64-a848-45b6-9c3a-47a01a4962eb

DELETE {{host}}/patients/{{patientId}}
authorization: Bearer {{authorization}}